// <auto-generated />
using ApiCoreEntity.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApiCoreEntity.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20171127182608_AddBlogAutorProp")]
    partial class AddBlogAutorProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCoreEntity.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor")
                        .HasMaxLength(60);

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("ApiCoreEntity.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BlogID");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ApiCoreEntity.Models.Post", b =>
                {
                    b.HasOne("ApiCoreEntity.Models.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogID");
                });
#pragma warning restore 612, 618
        }
    }
}
